SELECT
    EMPNO,
    FNAME,
    SEX,
    SALARY,
    WORKSTATUS,
    EMPLOYEE.DEPTCODE,
    DEPTNAME,
    SCTCODE,
    SCTTNAME,
    SPRCODE,
    SPRTNAME,
    SPVCODE,
    SPVTNAME
FROM
    EMPLOYEE
    INNER JOIN DEPARTMENT
    ON DEPARTMENT.DEPTCODE = EMPLOYEE.DEPTCODE
    INNER JOIN SETPROVINCE
    ON SETPROVINCE.SPVCODE = EMPLOYEE.SPVCODE
    INNER JOIN SETPART
    ON SETPART.SPRCODE = SETPROVINCE.SPVSPRCODE
    INNER JOIN SETCOUNTRY
    ON SETCOUNTRY.SCTCODE = SETPART.SPRSCTCODE
ORDER BY
    EMPLOYEE.EMPNO ASC;